name: Install CMake, Build then Test

on:
  push:

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      # install build dependencies
      # MUST match the same step in Dockerfile
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libboost-filesystem-dev libpng-dev

      - name: install "internal" dependencies
        # TODO yosys: use proper Release build
        run: |
          wget https://github.com/Interstellar-Network/yosys/releases/download/yosys-0.23-interstellar/yosys-0.1.1-Linux.deb -O yosys.deb
          sudo apt-get install -y --no-install-recommends ./yosys.deb
          wget https://github.com/Interstellar-Network/abc/releases/download/0.2.0/abc-0.1.1-Linux.deb -O abc.deb
          sudo apt-get install -y --no-install-recommends ./abc.deb

      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ inputs.ssh_key_input }}
          install_cmake_and_ninja: true

      - name: DEBUG cpuinfo
        run: |
          cat /proc/cpuinfo

      - uses: Interstellar-Network/gh-actions/cmake-build-and-test@v3-dev
